version: '3.5'

services:
    phpadmin:
        build:
            args:
                CONTAINER_VERSION: 1.0.1
                FROM_BASE: base_container:20180217
                MYSQL_PASSWORD: ${CFG_MYSQL_PASSWORD}
                MYSQL_ROOT_PASSWORD: ${CFG_MYSQL_ROOT_PASSWORD}
                MYSQL_USER: ${CFG_MYSQL_USER}
            cache_from:
                - alpine:3.6
                - base_container:20180217
            context: .
        container_name: phpadmin
        environment:
            MYSQL_PASSWORD: ${CFG_MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${CFG_MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${CFG_MYSQL_USER}
#            PMA_ARBITRARY: 1
#        external_links:
#            - db_server:db
        hostname: phpadmin
        image: phpadmin:20180217
#        links:
#            - "172.18.0.5":db
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        ports:
            - 8002:80
#        restart: unless-stopped
        volumes:
            - ../phpadmin/vols/log:/var/log
#           - ../phpadmin/vols/sessions       
