version: '3.1'

services:
    phpadmin:
        build:
            context: ../phpadmin
        image: phpadmin:20171219
        container_name: phpadmin
        hostname: phpadmin
        environment:
            TZ: "America/New_York"
            MYSQL_PASSWORD: ${CFG_MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${CFG_MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${CFG_MYSQL_USER}
#            - PMA_ARBITRARY=1
        ports:
            - 8002:80
        volumes:
            - ../phpadmin/vols/log:/var/log
#           - ../phpadmin/vols/sessions       
#        external_links:
#            - db_server:db
#        links:
#            - "172.18.0.5":db
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
