version: '3.3'

# repo: https://github/ballab1/phpmyadmin.git
# containerOS: alpine

services:
    phpmyadmin:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: phpmyadmin
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/php/${PHP7_VERSION:-7.2.8-r1}:${BASE_TAG:-latest}
                PHPMYADMIN_VERSION: ${PHPMYADMIN_VERSION:-4.8.3}
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}:${OS_VERSION:-3.8}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/supervisord:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/nginx-base/${NGINX_VERSION:-1.15.3}:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/php/${PHP7_VERSION:-7.2.8-r1}:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: phpmyadmin
                container.parent: $CONTAINER_PARENT
                version.cbf: $CBF_VERSION
        container_name: phpmyadmin
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
#            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_VERBOSE: 1
#            PWD_PROTECTED: 'true'
        hostname: phpmyadmin
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/phpmyadmin/${PHPMYADMIN_VERSION:-4.9.0.1}:${CONTAINER_TAG:-latest}
