version: '3.3'

# this is a SAMPLE file. Do not use for build or deployments

# use the following to restrict which OS this is built on
# containerOS: alpine

services:
    phpmyadmin:
# build arguments, only needed for building
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: phpmyadmin
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/php/${PHP7_VERSION:-7.2.22-r0}:${BASE_TAG:-latest}
                PHPMYADMIN_VERSION: ${PHPMYADMIN_VERSION:-4.8.3}
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}thirdparty/${CONTAINER_OS:-alpine}:${OS_VERSION:-3.8}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/supervisord:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/nginx-base/${NGINX_VERSION:-1.15.3}:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/php/${PHP7_VERSION:-7.2.22-r0}:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: phpmyadmin
                version.cbf: $CBF_VERSION
# common arguments, for building and deploy 
        container_name: phpmyadmin
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
#            MYSQL_PASSWORD_FILE: /run/secrets/mysql.pwd
#            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root.pwd
#            MYSQL_USER: $CFG_USER
#            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_PASSWORD_FILE: /run/secrets/pma.pwd
            PMA_PORT: 3306
            PMA_USER: $CFG_USER
            PMA_VERBOSE: 1
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd
            SUPERVISORD_USER: $CFG_USER
#            PWD_PROTECTED: 'true'
#            WEB_USER_ID: $CFG_USER
#            WEB_USER_PASS_FILE: /run/secrets/web_user.pwd
        hostname: phpmyadmin
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/phpmyadmin/${PHPMYADMIN_VERSION:-4.8.3}:${CONTAINER_TAG:-latest}
#        links:
#            - 172.18.0.5:mysql
# deploy arguments, not needed for building
        logging:                              # limit size of logs @runtime so that we do not run out of space 
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:                                #ports exposed 
            - 8002:80
        restart: unless-stopped               # only use when building a 'service container'
        secrets:                              # references to 'secrets' section below 
#            - mysql.pwd
#            - mysql_root.pwd
            - pma.pwd
            - supervisord.pwd
#            - web_user.pwd
        volumes:
            - ./vols/log:/var/log             # do not save aplication logs inside container 
#           - ./vols/sessions

# secrets only needed for deploy
secrets:                                      # location of secrets files in host filesystem 
   mysql.pwd:
     file: ~/.inf/secrets/bobb.password
   mysql_root.pwd:
     file: ~/.inf/secrets/bobb.password
   pma.pwd:
     file: ~/.inf/secrets/bobb.password
   supervisord.pwd:
     file: ~/.inf/secrets/bobb.password
